# ===== Sample queries for CityGML 2.0 Owl ===== #

# Basic prefixes
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX gml:  <http://www.opengis.net/gml#>
PREFIX core: <http://www.opengis.net/citygml/2.0#>
# CityGML module prefixes
PREFIX bldg: <http://www.opengis.net/citygml/building/2.0#>
PREFIX brid: <http://www.opengis.net/citygml/bridge/2.0#>
PREFIX luse: <http://www.opengis.net/citygml/landuse/2.0#>
PREFIX app:  <http://www.opengis.net/citygml/appearance/2.0#>
PREFIX dem:  <http://www.opengis.net/citygml/relief/2.0#>
PREFIX frn:  <http://www.opengis.net/citygml/cityfurniture/2.0#>
PREFIX gen:  <http://www.opengis.net/citygml/generics/2.0#>
PREFIX grp:  <http://www.opengis.net/citygml/cityobjectgroup/2.0#>
PREFIX tex:  <http://www.opengis.net/citygml/texturedsurface/2.0#>
PREFIX tun:  <http://www.opengis.net/citygml/tunnel/2.0#>
PREFIX veg:  <http://www.opengis.net/citygml/vegetation/2.0#>
PREFIX wtr:  <http://www.opengis.net/citygml/waterbody/2.0#>

# query all 

# query all buildings and their properties
SELECT *
WHERE {
?building rdf:type bldg:Building ;
   ?predicate ?object .
}

