### Sample queries for CityGML to RDF transformations ###

# Common prefixes
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
# CityGML module prefixes
PREFIX gml:  <http://www.opengis.net/gml#>
PREFIX xlink: <http://www.w3.org/1999/xlink#>
PREFIX core: <http://www.opengis.net/citygml/2.0#>
PREFIX bldg: <http://www.opengis.net/citygml/2.0/building#>
PREFIX brid: <http://www.opengis.net/citygml/2.0/bridge#>
PREFIX luse: <http://www.opengis.net/citygml/2.0/landuse#>
PREFIX app:  <http://www.opengis.net/citygml/2.0/appearance#>
PREFIX dem:  <http://www.opengis.net/citygml/2.0/relief#>
PREFIX frn:  <http://www.opengis.net/citygml/2.0/cityfurniture#>
PREFIX gen:  <http://www.opengis.net/citygml/2.0/generics#>
PREFIX grp:  <http://www.opengis.net/citygml/2.0/cityobjectgroup#>
PREFIX tex:  <http://www.opengis.net/citygml/2.0/texturedsurface#>
PREFIX tun:  <http://www.opengis.net/citygml/2.0/tunnel#>
PREFIX veg:  <http://www.opengis.net/citygml/2.0/vegetation#>
PREFIX wtr:  <http://www.opengis.net/citygml/2.0/waterbody#>
# GeoSPARQL prefixes
PREFIX units: <http://www.opengis.net/def/uom/OGC/1.0/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?s ?p ?o
WHERE {
	?s ?p ?o .
}


#1 query all buildings

#SELECT ?WallSurface
#WHERE {
#	?WallSurface rdf:type bldg:WallSurface .
#}


#2 query a building and it's properties

#SELECT ?building ?predicate ?object
#WHERE {
#	?building rdf:type bldg:Building ;
#		<wildcard>+ ?object .
#}


#3 query building boundary corner positions

#SELECT ?building ?lowerCornerPosition ?upperCornerPosition
#WHERE {
#?building rdf:type bldg:Building ;
#   gml:hasboundedBy ?boundedby .
#?boundedby gml:hasEnvelope ?envelope .
#?envelope rdf:type gml:Envelope ;
#   gml:lowerCorner ?lcorner ;
#   gml:upperCorner ?ucorner .
#?lcorner gml:hasdoubleList ?lowerCornerPosition .
#?ucorner gml:hasdoubleList ?upperCornerPosition .

#FILTER ( STR(?building) = "file:///home/diego/Documents/Repositories/UD-Graph/XSLT_Transformations/XML-to-OWL/Results/LYON_1ER_BATI_2015(1711_bldg).rdf#BU_69381AB243" ) .
#}


#4 query buildingpart solid surface member polygons and positions

#SELECT ?building ?polygon ?positions
#WHERE {
#?building rdf:type bldg:BuildingPart ;
#   bldg:lod2Solid ?solid .
#?solid gml:exterior ?exterior .
#?exterior gml:hassurfaceMember ?surface .
#?surface xlink:href ?polygon .
#?polygon gml:hasexterior ?exterior2 .
#?exterior2 gml:has_Ring ?ring .
#?ring gml:hasposList ?posList .
#?posList gml:hasdoubleList ?positions .

#FILTER ( STR(?building) = "file:///home/diego/Documents/Repositories/UD-Graph/XSLT_Transformations/XML-to-OWL/Results/LYON_1ER_BATI_2015(1711_bldg).rdf#BU_69381AB243_1" ) .
#}


#5 query all GeoSPARQL features with GML serializations

#SELECT ?feature ?serialization
#WHERE {
#?feature geo:hasGeometry ?geometry .

#?geometry geo:asGML ?serialization .
#}


#6 query all GeoSPARQL features within 10 m of a point 

#SELECT DISTINCT ?feature ?type
#WHERE {
#?feature geo:hasGeometry ?geometry ;
#	rdf:type ?type .
#   
#?geometry geo:asGML ?serialization .

#FILTER (geof:distance("<gml:Point xmlns:gml=\"http://www.opengis.net/ont/gml\" srsName=\"EPSG:4326\">
#							<gml:pos>45.854617529132426 4.797614456250814 404</gml:pos>
#						</gml:Point>"^^geo:gmlLiteral,
#	?serialization , units:metre ) < 10) .
#}

LIMIT 25